name: Target Branch PR Check
on:
    pull_request:
        types: [opened, synchronize, edited]
jobs:
    pr-branch-confirmation:
        name: Confirm that target branch for PR is development or build/
        if: ${{ github.actor != 'dependabot[bot]' }}
        runs-on: ubuntu-18.04
        steps:
            - name: Set PR title validity
              id: is-valid
              if: >
                  startsWith(github.event.pull_request.base.ref, 'development')||
                  startsWith(github.event.pull_request.base.ref, 'build/')
              run: |
                  OUTPUT=true
                  echo "::set-output name=isValid::$OUTPUT"
            - name: echo isValid
              run: |
                  echo ${{ steps.is-valid.outputs.isValid }}
            - name: PR title is valid
              if: ${{steps.is-valid.outputs.isValid == 'true'}}
              run: |
                  echo 'Pull request target branch is valid.'
                  echo ${{ steps.is-valid.outputs.isValid }}
            - name: PR title is invalid
              if: ${{ steps.is-valid.outputs.isValid != 'true'}}
              run: |
                  echo ${{ steps.is-valid.outputs.isValid }}
                  echo 'Pull request target branch is not valid.'
                  exit 1
